name: freev
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pytorch::pytorch=2.5.1
  - pytorch::torchaudio=2.5.1
  - pytorch-cuda=12.4
  - conda-forge::einops
  - conda-forge::librosa
  - conda-forge::matplotlib
  - conda-forge::numpy
  - conda-forge::scipy
  - conda-forge::pysoundfile
  - conda-forge::tensorboard
  - pip:
      - -e . --no-deps